server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index Archivo_de_Planos_Históricos.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    # Sin caché mientras desarrollás, así ves los cambios del HTML al recargar
    add_header Cache-Control "no-cache";
}
